#SPDX-License-Identifier: MIT-0
---
# tasks file for bdd
- name: Install Postgresql
  become: yes
  apt:
    name:
      - postgresql-14
      - acl
      - python3-psycopg2

- name: Create group
  become: yes
  group:
    name: "{{ bdd_group }}"

- name: Create user
  become: yes
  user:
    name: "{{ bdd_user }}"
    group: "{{ bdd_group }}"

- name: Create database role
  become: yes
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ bdd_user }}"
    role_attr_flags: SUPERUSER

- name: Init database
  become: yes
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ bdd_db }}"
    owner: "{{ bdd_user }}"

- name: Set database listen address
  become: yes
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    line: "listen_addresses = '*'"
    search_string: "listen_addresses = "
  notify: Restart Postgresql

- name: Set database policy
  become: yes
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/14/main/pg_hba.conf
    contype: host
    users: "{{ bdd_user }}"
    source: "{{ bdd_api_host }}"
    databases: "{{ bdd_db }}"
    method: ident
    create: true
  notify: Restart Postgresql

- name: Copy SQL script
  template:
    src: ../templates/init.sql.j2
    dest: /tmp/init.sql

- name: Run SQL script
  become: yes
  become_user: "{{ bdd_user }}"
  community.postgresql.postgresql_script:
    login_user: "{{ bdd_user }}"
    db: "{{ bdd_db }}"
    path: /tmp/init.sql
