#SPDX-License-Identifier: MIT-0
---
# tasks file for app
- name: Install packages
  become: yes
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - libpq-dev
      - acl
      - oidentd

- name: Create user
  become: yes
  user:
    name: "{{ app_user }}"

- name: Create app directory
  become: yes
  become_user: "{{ app_user }}"
  file:
    path: "{{ app_app_dir }}"
    state: directory

- name: Copy app
  become: yes
  become_user: "{{ app_user }}"
  copy:
    src: ../files/app
    dest: "{{ app_app_dir }}/.."

- name: Init virtual env and dependencies
  become: yes
  become_user: "{{ app_user }}"
  pip:
    chdir: "{{ app_app_dir }}"
    requirements: requirements.txt
    virtualenv: "{{ app_venv_path }}"
    virtualenv_command: python3 -m venv

- name: Apply template
  become: yes
  template:
    src: ../templates/app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd config files
  become: yes
  systemd_service:
    daemon_reload: true

- name: Setup service
  become: yes
  systemd_service:
    name: app
    state: restarted
    enabled: yes

- name: Wait 3 seconds
  become: yes
  pause:
    seconds: 3

- name: Do a request on the api
  uri:
    url: http://localhost:8080/api/users
    return_content: true
  register: req_response

- name: Show the response
  debug:
    var: req_response['json']
